Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use('seaborn')
import statsmodels.api as sm
from statsmodels.formula.api import ols
from linearmodels.iv import IV2SLS
from scipy.stats import zscore
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_22012/3483673392.py[0m in [0;36m<module>[1;34m[0m
[0;32m      5[0m [1;32mimport[0m [0mstatsmodels[0m[1;33m.[0m[0mapi[0m [1;32mas[0m [0msm[0m[1;33m[0m[1;33m[0m[0m
[0;32m      6[0m [1;32mfrom[0m [0mstatsmodels[0m[1;33m.[0m[0mformula[0m[1;33m.[0m[0mapi[0m [1;32mimport[0m [0mols[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 7[1;33m [1;32mfrom[0m [0mlinearmodels[0m[1;33m.[0m[0miv[0m [1;32mimport[0m [0mIV2SLS[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      8[0m [1;32mfrom[0m [0mscipy[0m[1;33m.[0m[0mstats[0m [1;32mimport[0m [0mzscore[0m[1;33m[0m[1;33m[0m[0m

[1;31mModuleNotFoundError[0m: No module named 'linearmodels'
ModuleNotFoundError: No module named 'linearmodels'

