Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Para que sea replicable, fijamos un valor para la funci√≥n  `np.random.seed`.
np.random.seed(1)
T = 121
e = np.random.randn(T)
e[0] = 0

x0 = y0 = a = 1
t = np.arange(T)

y = y0 + a*t + e.cumsum()
x = x0 + a*t + e

fig, ax = plt.subplots()
pd.DataFrame({'DS': y, 'TS': x}).plot(ax=ax)
ax.set_title('Tendencia determin√≠stica (TS) versus estoc√°stica (DS)', fontsize=16)
fig.suptitle('Series no estacionarias',fontsize=24, y=1.05)
fig
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_14196/1350431538.py[0m in [0;36m<module>[1;34m[0m
[0;32m     11[0m [0mx[0m [1;33m=[0m [0mx0[0m [1;33m+[0m [0ma[0m[1;33m*[0m[0mt[0m [1;33m+[0m [0me[0m[1;33m[0m[1;33m[0m[0m
[0;32m     12[0m [1;33m[0m[0m
[1;32m---> 13[1;33m [0mfig[0m[1;33m,[0m [0max[0m [1;33m=[0m [0mplt[0m[1;33m.[0m[0msubplots[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     14[0m [0mpd[0m[1;33m.[0m[0mDataFrame[0m[1;33m([0m[1;33m{[0m[1;34m'DS'[0m[1;33m:[0m [0my[0m[1;33m,[0m [1;34m'TS'[0m[1;33m:[0m [0mx[0m[1;33m}[0m[1;33m)[0m[1;33m.[0m[0mplot[0m[1;33m([0m[0max[0m[1;33m=[0m[0max[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m     15[0m [0max[0m[1;33m.[0m[0mset_title[0m[1;33m([0m[1;34m'Tendencia determin√≠stica (TS) versus estoc√°stica (DS)'[0m[1;33m,[0m [0mfontsize[0m[1;33m=[0m[1;36m16[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mNameError[0m: name 'plt' is not defined
NameError: name 'plt' is not defined

