Traceback (most recent call last):
  File "/home/randall/anaconda3/envs/libro-ec4301/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/randall/anaconda3/envs/libro-ec4301/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/randall/anaconda3/envs/libro-ec4301/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/randall/anaconda3/envs/libro-ec4301/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/randall/anaconda3/envs/libro-ec4301/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/randall/anaconda3/envs/libro-ec4301/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/home/randall/anaconda3/envs/libro-ec4301/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/randall/anaconda3/envs/libro-ec4301/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
datos <- read.csv("../data/log-imae.csv", stringsAsFactors=FALSE) %>%
  mutate(mes = yearmonth(X)) %>%
  as_tsibble(index=mes) %>%
  select(mes, Original, Tendencia.ciclo)
------------------

Error: A valid tsibble must have distinct rows identified by key and index.
[34mâ„¹[39m Please use `duplicates()` to check the duplicated rows.
Traceback:

1. read.csv("../data/log-imae.csv", stringsAsFactors = FALSE) %>% 
 .     mutate(mes = yearmonth(X)) %>% as_tsibble(index = mes) %>% 
 .     select(mes, Original, Tendencia.ciclo)
2. select(., mes, Original, Tendencia.ciclo)
3. as_tsibble(., index = mes)
4. as_tsibble.data.frame(., index = mes)
5. build_tsibble(x, key = !!enquo(key), index = !!index, interval = regular, 
 .     validate = validate, .drop = .drop)
6. validate_tsibble(data = tbl, key = key_vars, key_data = key_data, 
 .     index = index)
7. abort(c("A valid tsibble must have distinct rows identified by key and index.", 
 .     i = "Please use `duplicates()` to check the duplicated rows."))
8. signal_abort(cnd)
ERROR: Error: A valid tsibble must have distinct rows identified by key and index.
[34mâ„¹[39m Please use `duplicates()` to check the duplicated rows.


